# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assetbuild}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Jeffers"]
  s.date = %q{2010-04-08}
  s.description = %q{Easily merge and compress multiple asset files together (currently supports CSS and coffee-script).}
  s.email = %q{shout@jimjeffers.com}
  s.executables = ["assetbuild", "buildcoffee", "buildcss"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "Manifest",
     "README",
     "Rakefile",
     "VERSION",
     "bin/assetbuild",
     "bin/buildcoffee",
     "bin/buildcss",
     "demo/assetbuild.yml",
     "demo/assets.css",
     "demo/coffee_bundle/demo.coffee",
     "demo/coffee_bundle/demo2.coffee",
     "demo/main.js",
     "demo/secondary.css",
     "demo/stand_alone.coffee",
     "demo/stand_alone.js",
     "demo/styles/reset.css",
     "demo/styles/special/basic_stuff.css",
     "demo/styles/special/more_stuff.css",
     "demo/styles/typography.css",
     "demo/test.css",
     "lib/asset_build.rb",
     "lib/asset_build/coffee_bundler.rb",
     "lib/asset_build/css_reader.rb",
     "spec/asset_build_spec.rb",
     "spec/coffee_bundler_spec.rb",
     "spec/css_reader_spec.rb"
  ]
  s.homepage = %q{http://github.com/jimjeffers/assetbuild}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Easily merge and compress multiple asset files together (currently supports CSS and coffee-script).}
  s.test_files = [
    "spec/asset_build_spec.rb",
     "spec/coffee_bundler_spec.rb",
     "spec/css_reader_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

